/**
 * Database model interfaces — mirrors the Supabase schema.
 * No business logic; just shape definitions.
 */

// ───── Enums / Literals ─────

export type UserRole = "user" | "admin";
export type Gender = "male" | "female" | "other";

// ───── Profiles table ─────

export interface Profile {
    id: string;
    role: UserRole | null;
    name: string | null;
    gender: Gender | null;
    bio: string | null;
    is_pro: boolean | null;
}

// ───── Reports table ─────

export interface Report {
    id: string;
    user_id: string;
    interest_score: number;
    initiative_user: number;
    initiative_partner: number;
    sentiment_history: number[];
    advice: string[];
    summary: string;
    chat_preview: string | null;
    created_at: string;
}

/**
 * The subset of Report fields required when inserting a new row.
 * `id` and `created_at` are auto-generated by Supabase.
 */
export type ReportInsert = Omit<Report, "id"> & { id?: string };
